language: ruby
rvm: 2.2
before_install:
  - nvm install 6
install: script/bootstrap
script: script/cibuild
cache:
  bundler: true
  directories:
    - node_modules
sudo: false
env:
  matrix:
    - TEST_SUITE=node
    - TEST_SUITE=ruby
