language: ruby
rvm: 2.4
before_install:
  - nvm install 6
  - gem update --system --no-document
  - bundle config path vendor/bundle
install: script/bootstrap
script: script/cibuild
cache:
  yarn: true
  directories:
    - vendor/bundle
    - node_modules
env:
  matrix:
    - TEST_SUITE=node
    - TEST_SUITE=ruby JEKYLL_VERSION="~> 3.8"
    - TEST_SUITE=ruby JEKYLL_VERSION="~> 4.0"
after_success:
  - npm run test:cover:CI
branches:
  only:
    - master
