environment:
  nodejs_version: "6"
  RACK_ENV: test
  JEKYLL_LOG_LEVEL: warn
  RUBY_VERSION: 22
  matrix:
    - TEST_SUITE: node
    - TEST_SUITE: ruby

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - gem install bundler --no-ri --no-rdoc
  - sh script/bootstrap

build: off

before_test:
  - node --version
  - npm --version
  - ruby -v
  - gem -v
  - bundle -v

after_test:
  - bundle package

test_script:
  - sh script/cibuild

cache:
  - vendor/cache
  - node_modules

init:
  - git config --global core.autocrlf true
