environment:
  nodejs_version: "0"
  RACK_ENV: test
  JEKYLL_LOG_LEVEL: warn

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - bundle config --local path vendor/bundle
  - bundle install
  - npm install

build: off

before_test:
  - node --version
  - npm --version
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - npm test
  - bundle exec rspec
  - bundle exec rubocop -D -S

cache:
  - vendor/bundle

init:
  - git config --global core.autocrlf true
