environment:
  nodejs_version: "6"
  RACK_ENV: test
  JEKYLL_LOG_LEVEL: warn

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - ps: Install-Product node $env:nodejs_version
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs=3 --retry=3 --path=vendor/bundle
  - npm install

build: off

before_test:
  - node --version
  - npm --version
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - npm test
  - bundle exec rspec
  - bundle exec rubocop -D -S
  - gem build jekyll-admin.gemspec

cache:
  - vendor/bundle
  - node_modules

init:
  - git config --global core.autocrlf true
