title: Jekyll Admin
description: A Jekyll plugin that provides users with a traditional CMS-style graphical interface to author content and administer Jekyll sites.

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

theme: minima

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
